module.exports = [
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tStaff DevOps Engineer\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-staff-devops-engineer-bugcrowd-1129507",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tForward Deployed Engineer AI Inference\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-forward-deployed-engineer-ai-inference-red-hat-inc-1129504",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tSenior Software Developer\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-senior-software-developer-vidyard-1129492",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tSenior Java Software Developer\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-senior-java-software-developer-callibrity-1129479",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tSenior Full Stack Developer\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-senior-full-stack-developer-nuclear-promise-x-1129478",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tProduct Engineer AuthKit\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-product-engineer-authkit-workos-1129477",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tSoftware Engineer Site Reliability Engineer\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-software-engineer-site-reliability-engineer-thumbtack-1129471",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tStaff Software Engineer Java\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-staff-software-engineer-java-ping-identity-1129467",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tJunior Software Developer Full Stack\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-junior-software-developer-full-stack-koho-1129454",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tSenior HubSpot Developer\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-senior-hubspot-developer-softermii-1129453",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tAI Developer 1551\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-ai-developer-1551-highstreet-1129439",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tSecurity Architect\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-security-architect-dexterity-1129385",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tSenior Infrastructure Engineer\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-senior-infrastructure-engineer-paradigm-health-1129369",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tSenior Software Developer II Cloud\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-senior-software-developer-ii-cloud-life360-1129368",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tFull Stack Developer\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-full-stack-developer-microventures-1129364",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tDevOps Software Engineer Energy Storage\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-devops-software-engineer-energy-storage-redwood-materials-1129354",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tSenior DevOps Engineer\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-senior-devops-engineer-little-thinking-minds-1129296",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tFull Stack Software Engineer III Angular Java\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-full-stack-software-engineer-iii-angular-java-meridianlink-1129290",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tSoftware Engineer I Dev Tooling\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-software-engineer-i-dev-tooling-sumo-logic-1129266",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tDistributed Systems Engineer\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-distributed-systems-engineer-livekit-1129265",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tEvents Marketing Manager\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-events-marketing-manager-alpaca-1129242",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tPHP Laravel Developer Needed ROCKSTARS ONLY\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-php-laravel-developer-needed-rockstars-only-agent-legend-1129233",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tSenior Software Engineer Platform\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-senior-software-engineer-platform-omada-health-1129228",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tSenior DevOps Engineer\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-senior-devops-engineer-inkitt-1129224",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tStaff DevOps Engineer\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-staff-devops-engineer-heartflow-1129216",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tMid C# Fullstack Developer\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-mid-c-fullstack-developer-zipdev-1129205",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tTypeScript Developer\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-typescript-developer-stoke-studio-1129195",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tSenior Frontend Developer\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-senior-frontend-developer-sanctuary-computer-1129194",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tSenior Backend Engineer\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-senior-backend-engineer-goodnotes-1129185",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tProduct Manager\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-product-manager-conduit-1129162",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tCloud Architect NodeJs React\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-cloud-architect-nodejs-react-3pillar-1129146",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tSoftware Engineer II\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-software-engineer-ii-horace-mann-1129121",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tSenior DevOps Engineer\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-senior-devops-engineer-alpaca-1129119",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tSenior Exploit Developer\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-senior-exploit-developer-vulncheck-1129099",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tTechnical Customer Success Manager\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-technical-customer-success-manager-dv-labs-1129095",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tSenior Application Engineer\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-senior-application-engineer-infstones-1129086",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tSoftware Developer\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-software-developer-benzinga-1129083",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tDevOps Engineer\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-devops-engineer-infstones-1129074",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tPrincipal Engineer Asp.Net\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-principal-engineer-asp-net-wisecode-1129022",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tDevOps Engineer\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-devops-engineer-happyco-1129015",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tFull Stack Engineer Developer Portal\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-full-stack-engineer-developer-portal-helius-1128980",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tData Scientist GeoAI\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-data-scientist-geoai-esri-1128979",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tVice President Senior Frontend Developer\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-vice-president-senior-frontend-developer-galaxy-1128977",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tCustomer Success Manager\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-customer-success-manager-livekit-1128976",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tFull Stack Engineer\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-full-stack-engineer-darkroom-1128975",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tTechnical Project Manager\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-technical-project-manager-tether-operations-limited-1128945",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tAssoc Protocol Engineer\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-assoc-protocol-engineer-galaxy-digital-services-1128893",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tDirector of Payments U.S. Canada\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-director-of-payments-u-s-canada-banyan-software-1128873",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tSenior Environment Concept Artist Contract\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-senior-environment-concept-artist-contract-arenanet-1128872",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tSenior Creature Concept Artist Contract\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-senior-creature-concept-artist-contract-arenanet-1128871",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tSenior Concept Artist Contract\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-senior-concept-artist-contract-arenanet-1128870",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tMid level Full Stack Engineer HRPS PK\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-mid-level-full-stack-engineer-hrps-pk-smart-working-solutions-1128858",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tFrontend Tech Lead\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-frontend-tech-lead-airdna-1128840",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tSenior Environment Artist Contract\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-senior-environment-artist-contract-arenanet-1128837",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tSoftware Engineer Generalist Devops\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-software-engineer-generalist-devops-aztec-1128832",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tEnterprise Account Executive NA West\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-enterprise-account-executive-na-west-akuity-1128816",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tSenior iOS Developer\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-senior-ios-developer-web-summit-1128815",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tExploit Developer\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-exploit-developer-vulncheck-1128813",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tSenior Full Stack Developer .Net and Angular\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-senior-full-stack-developer-net-and-angular-ubiminds-1128797",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tInside Sales Associate\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-inside-sales-associate-liatrio-1128791",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tTrade Operations Manager\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-trade-operations-manager-cleanspark-1128769",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tGrowth Consultant LATAM\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-growth-consultant-latam-ava-labs-1128768",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tSenior Golang Developer\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-senior-golang-developer-group-ib-1128764",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tTechnical Product Manager Connectors\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-technical-product-manager-connectors-conductorone-1128730",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tFrontend Engineer\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-frontend-engineer-supabase-1128728",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tML Solutions Architect\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-ml-solutions-architect-provectus-1128724",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tSenior Software Developer\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-senior-software-developer-varicent-1128699",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tJob 25535 Master Fullstack Developer Brazil\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-job-25535-master-fullstack-developer-brazil-ciampt-1128672",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tjob 24824 Junior Drupal Developer Brazil\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-job-24824-junior-drupal-developer-brazil-ciampt-1128671",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tEnterprise Account Executive\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-enterprise-account-executive-semgrep-1128654",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tSenior Application Security Engineer\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-senior-application-security-engineer-uniswap-labs-1128632",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tTechnical Project Manager\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-technical-project-manager-subzero-labs-1128613",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tAWS CLOUD NATIVE DEVELOPER\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-aws-cloud-native-developer-cook-systems-1128611",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tInfra DevOps Engineer Specialist\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-infra-devops-engineer-specialist-invisible-agency-1128581",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tFull Stack Engineer Specialist\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-full-stack-engineer-specialist-invisible-agency-1128572",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tFull Stack Developer\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-full-stack-developer-bisnow-1128563",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tSenior Golang Full Stack Developer\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-senior-golang-full-stack-developer-grax-1128539",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tHead of Platform Engineering\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-head-of-platform-engineering-ethena-labs-1128540",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\t*SR DevOps Data engineer\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-sr-devops-data-engineer-coderio-1128534",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tPartner Marketing Manager\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-partner-marketing-manager-honeycomb-1128523",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tSenior Software Engineer\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-senior-software-engineer-acquia-1128508",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tSoftware Developer\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-software-developer-higher-logic-1128506",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tDevOps Engineer\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-devops-engineer-nansen-ai-1128501",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tParalegal Capital Markets\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-paralegal-capital-markets-goodleap-1128481",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tSenior Manager Martech Developer Digital Banking\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-senior-manager-martech-developer-digital-banking-forbright-bank-1128475",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tSoftware Engineer\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-software-engineer-skyward-it-solutions-llc-1128469",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tSenior Software Engineer\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-senior-software-engineer-ennoble-care-1128463",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tDevOps Engineer\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-devops-engineer-netbox-labs-1128455",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tStaff Engineer\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-staff-engineer-the-block-1128446",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tSenior Full Stack Software Engineer Financial Reports Team\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-senior-full-stack-software-engineer-financial-reports-team-houzz-1128438",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tSalesforce Full Stack Developer\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-salesforce-full-stack-developer-culligan-quench-1128435",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tBackend Developer\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-backend-developer-forta-1128424",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tFront End Developer Sr\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-front-end-developer-sr-valtech-1128402",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "RemoteOK",
    "role": "\n\t\t\t\t\tLand Acquisition Director\t\t\t\t",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://remoteOK.com/remote-jobs/remote-land-acquisition-director-bisnow-1128401",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "WeWorkRemotely",
    "role": "Zencastr: Senior Backend Engineer - Full Remote",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://weworkremotely.com/remote-jobs/zencastr-senior-backend-engineer-full-remote",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "WeWorkRemotely",
    "role": "Storetasker: Senior Shopify Developer (Remote + Flexible)",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://weworkremotely.com/remote-jobs/storetasker-senior-shopify-developer-remote-flexible-3",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "WeWorkRemotely",
    "role": "WodBoard: Senior Rails developer",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://weworkremotely.com/remote-jobs/wodboard-senior-rails-developer-1",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "WeWorkRemotely",
    "role": "OnTheGoSystems: Senior Python Developer",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://weworkremotely.com/remote-jobs/onthegosystems-senior-python-developer",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "WeWorkRemotely",
    "role": "Enrollio: Senior Full-Stack TypeScript Engineer (NestJS + React) – SaaS Platform",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://weworkremotely.com/remote-jobs/enrollio-senior-full-stack-typescript-engineer-nestjs-react-saas-platform",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "WeWorkRemotely",
    "role": "KFC: Sr. Software Engineer II",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://weworkremotely.com/remote-jobs/kfc-sr-software-engineer-ii",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "WeWorkRemotely",
    "role": "Growth Factory Ventures: Applied AI Engineer",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://weworkremotely.com/remote-jobs/growth-factory-ventures-applied-ai-engineer",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "WeWorkRemotely",
    "role": "PostHog: Product Engineer - Data Modeling",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://weworkremotely.com/remote-jobs/posthog-product-engineer-data-modeling",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "WeWorkRemotely",
    "role": "PostHog: AI Product Engineer",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://weworkremotely.com/remote-jobs/posthog-ai-product-engineer",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "WeWorkRemotely",
    "role": "comparis.ch: Experienced Full-Stack Software Engineer (.NET/React), 80–100% (f/m/x), fully remote",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://weworkremotely.com/remote-jobs/comparis-ch-experienced-full-stack-software-engineer-net-react-80-100-f-m-x-fully-remote",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "WeWorkRemotely",
    "role": "Sticker Mule: Software engineer",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://weworkremotely.com/remote-jobs/sticker-mule-software-engineer-1",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "WeWorkRemotely",
    "role": "Remote Leverage: Senior Full Stack MERN Developer",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://weworkremotely.com/remote-jobs/remote-leverage-senior-full-stack-mern-developer",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "WeWorkRemotely",
    "role": "Stack Influence: Senior Full Stack Javascript Engineer (Remote, 4-day week)",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://weworkremotely.com/remote-jobs/stack-influence-senior-full-stack-javascript-engineer-remote-4-day-week",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "WeWorkRemotely",
    "role": "Silverfin: Player-Coach Engineering Team Lead",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://weworkremotely.com/remote-jobs/silverfin-player-coach-engineering-team-lead-1",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "WeWorkRemotely",
    "role": "Silverfin: Experienced Ruby Product Engineer",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://weworkremotely.com/remote-jobs/silverfin-experienced-ruby-product-engineer-1",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "WeWorkRemotely",
    "role": "Stellar AI: Senior Software Engineer",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://weworkremotely.com/remote-jobs/stellar-ai-senior-software-engineer",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "WeWorkRemotely",
    "role": "Close: Senior Software Engineer - Backend/Python - USA Only (100% Remote)",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://weworkremotely.com/remote-jobs/close-senior-software-engineer-backend-python-usa-only-100-remote-1",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "WeWorkRemotely",
    "role": "Proton.ai: Senior Backend Engineer",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://weworkremotely.com/remote-jobs/proton-ai-senior-backend-engineer",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "WeWorkRemotely",
    "role": "Lincoln Freedom Group, LLC: Python Developer - Code Quality & Standards (US Only)",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://weworkremotely.com/remote-jobs/lincoln-freedom-group-llc-python-developer-code-quality-standards-us-only",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "WeWorkRemotely",
    "role": "Lincoln Freedom Group, LLC: Python Developer (US Only)",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://weworkremotely.com/remote-jobs/lincoln-freedom-group-llc-python-developer-us-only",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "WeWorkRemotely",
    "role": "DynamiCare Health: Full-Stack Engineer",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://weworkremotely.com/remote-jobs/dynamicare-health-full-stack-engineer",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "WeWorkRemotely",
    "role": "Proxify AB: Senior Fullstack Developer (Python)",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://weworkremotely.com/remote-jobs/proxify-ab-senior-fullstack-developer-python",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "WeWorkRemotely",
    "role": "Proxify AB: Senior Ruby on Rails Developer",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://weworkremotely.com/remote-jobs/proxify-ab-senior-ruby-on-rails-developer-2",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "WeWorkRemotely",
    "role": "Proxify AB: Senior Backend Developer (Python)",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://weworkremotely.com/remote-jobs/proxify-ab-senior-backend-developer-python-5",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  },
  {
    "company": "WeWorkRemotely",
    "role": "Proxify AB: Senior Fullstack Developer (React.js & Node.js)",
    "recruiterName": "Not specified",
    "recruiterEmail": "not_available",
    "link": "https://weworkremotely.com/remote-jobs/proxify-ab-senior-fullstack-developer-react-js-node-js-1",
    "dateApplied": null,
    "status": "not_applied",
    "followUpSent": false,
    "dateAdded": "2026-01-11"
  }
]